### ISSUE TITLE
Allow controls for no-password Pi-holes

### ISSUE THREAD

**Issue by amiantos** [amiantos/pibar#11]
From [this user on reddit](https://www.reddit.com/r/pihole/comments/gomprz/pibar_for_macos_v10_query_stats_controls_in_your/frhn7k7/), when you have a pi-hole that has been set up to have no password, you can authenticate to the api by appending an empty `auth` query string to the endpoint. Nifty!

Will support this in 1.1.

## Workaround
You can get around this requirement in version 1.0 by putting anything in the "API Token" box and hitting Test, then Save. No need to set a password on your pi-hole instance to get around it.

**Comment by amiantos** [comment]
I figure I'll just need to add an option to enable this, when you add a Pi-hole. Maybe a checkbox that says "No Auth" or something to signal that no API token is needed to manage it.

**Comment by pquodling** [comment]
Ditto on this - got the "no password set" message, went looking for my API Token - doesn't appear to be one, and little in the way of clear instructions on how to set one.

**Comment by amiantos** [comment]
To set a password on your Pi-hole you can follow these instructions: https://discourse.pi-hole.net/t/how-do-i-set-or-reset-the-web-interface-password/1328

In the meantime, if you don't want to do that, I wonder if you can just set a fake API token in PiBar and it'll let you enable/disable your Pi-hole. If you try that out, please let us know if it works. Sorry for the trouble, I didn't even realize this was a thing!

**Comment by rross101** [comment]
Fake API token worked for me. Thanks!

**Comment by amiantos** [comment]
A fix for this is now in beta: https://www.reddit.com/r/PiBar/comments/grnapv/pibar_for_macos_v11_beta/
