### ISSUE TITLE
Feature: Re-enable Pi-hole

### ISSUE THREAD

**Issue by Coder84619** [amiantos/pibar#29]
I don't know if this is possible via API, but it would be very handy to have a manual re-enable pi-hole option. Why? Let's say I disable Pi-hole for 5 minutes, go to my blocked site, and then want to turn Pi-hole back in sooner than the 5 minute timeout. Let me do that from Pi-bar.

**Comment by amiantos** [comment]
You can already do that from PiBar, once all your Pi-holes are disabled the "Disable Pi-hole" button turns into "Enable Pi-hole". You can see that in [the bottom right screenshot](https://raw.githubusercontent.com/amiantos/pibar/master/.github/screenshots.jpg). Let me know if I am misunderstanding your request...

**Comment by Coder84619** [comment]
Whoops..I'm blind as a bat! Thanks....you got it covered.
