### ISSUE TITLE
"Launch at login" does not work

### ISSUE THREAD

**Issue by bondskin** [amiantos/pibar#32]
On my MacBook I have enabled the "Launch at login" option in PiBar.
However, after restarting my MacOS it is not started automatically

**Comment by amiantos** [comment]
What version of macOS are you running? It technically shouldn't matter, but I'm curious. I am using  [this package](https://github.com/sindresorhus/LaunchAtLogin) and it seems to be working for me.

For others impacted by this, it's [relatively easy to add an app to Login Items yourself](https://support.apple.com/guide/mac-help/open-items-automatically-when-you-log-in-mh15189/mac).

**Comment by bondskin** [comment]
10.15.5

**Comment by amiantos** [comment]
Hmm... same as me. I wonder why it isn't working for you, but works for me. Very curious...

**Comment by bondskin** [comment]
I tried again, it works as designed. I guess a local issue here.
Thanks for your help.
All good now
