### ISSUE TITLE
Running Pi-Hole in Docker Desktop

### ISSUE THREAD

**Issue by Deim0s13** [amiantos/pibar#39]
Hi,
More of a question than a bug, but will pibar work if I am running my Pi-Hole within a docker container using Docker Desktop on my MacBook Pro?
Thanks,
Patrick Leathen

**Comment by amiantos** [comment]
Yes! I run a Pi-hole in Docker on a iMac sitting in a closet and PiBar works just fine with it. Nothing special with my setup either, pretty sure I just followed the normal docker setup tutorial.

![image](https://user-images.githubusercontent.com/1126616/98835484-54b46400-23f5-11eb-95cc-1a48ff0e3b3a.png)
