### ISSUE TITLE
Feature Request: Apple Silicon Support

### ISSUE THREAD

**Issue by PappyChappy1** [amiantos/pibar#41]
PiBar still runs under intel architecture, is it possible to port over to support the new M1 Macs?

**Comment by amiantos** [comment]
I assume that's not hard to do, I can possibly push a version update for this in the next few days.

**Comment by felix-mcfly** [comment]
Anything new here? Would be very nice to have a native Version that runs without rosetta2 and saves battery.

**Comment by amiantos** [comment]
Sorry, life got in the way. I'll get it out this week!

**Comment by amiantos** [comment]
@PappyChappy1 @felix-mcfly can you test this build out to make sure it works? https://amiantos.s3.amazonaws.com/PiBar-1.1.1.zip

**Comment by felix-mcfly** [comment]
Works like a charm on my M1 MacBook Pro! Thanks for your work mate! 🚀

**Comment by PappyChappy1** [comment]
Works for me as well - showing as Universal, not Intel.  I’m on M1 Mac mini.

**Comment by felix-mcfly** [comment]
also in activity monitor pihole shows up as "Apple" architecture now and says ARM64 in analysis.

<img width="903" alt="Bildschirmfoto 2021-02-17 um 20 38 53" src="https://user-images.githubusercontent.com/37754598/108258418-4302fb00-7160-11eb-859b-342ee79196c6.png">

**Comment by amiantos** [comment]
Fantastic. Thank you both!
