### ISSUE TITLE
Latest update (AdminLTE 5.18) breaks PiBar

### ISSUE THREAD

**Issue by Duoaccess** [amiantos/pibar#46]
After the last update of FTL an Webinterface, Pibar can´t access data of Pi-hole. [https://pi-hole.net/blog/2022/11/17/upcoming-changes-authentication-for-more-api-endpoints-required/#page-content](url) might be the reason. Will there be an update of Pi-hole in the near future?

**Comment by Larrikinau** [comment]
I also have the same issue. Would love to see an update to fix this. Thanks!

**Comment by Larrikinau** [comment]
@amiantos Hi Brad - just wondering if you are still maintaining Pibar. If so, would greatly appreciate it when time permits if you could look at the above?  With thanks (and a massive fan of your app!).

**Comment by amiantos** [comment]
Hi! Yes I am still maintaining PiBar, but I've been on vacation so I didn't notice this issue until now, apologies!

I am moving the end of this week so I can't promise anything is going to happen this week, but I'll see if I can throw something together to account for any changes in the Pi-hole API.

**Comment by Larrikinau** [comment]
Thanks @amiantos. Greatly appreciate it. Best wishes with your move!

**Comment by amiantos** [comment]
I'll get this handled today. Sorry for the delay everyone!

**Comment by amiantos** [comment]
This should work. Unfortunately I had to remove "Launch at Login" support as it no longer supports macOS 10.12, which is a hard requirement for this project so it supports pre-SwiftUI versions of macOS.

https://amiantos.s3.amazonaws.com/PiBar-1.1.2.zip

Please try this out locally and let me know if it works, then I can push it to the App Store.

**Comment by amiantos** [comment]
Seems like this is good testing locally, I am pushing to the App Store ASAP.

**Comment by amiantos** [comment]
PiBar 1.1.2 has been submitted to App Review.

**Comment by amiantos** [comment]
Closing this issue as fixed in https://github.com/amiantos/pibar/pull/50

**Comment by amiantos** [comment]
Approved for App Store, should be live soon... too bad I forgot to update the version number in the About dialog :(

**Comment by Uwedus** [comment]
When updating to 1,1,2 due login to autostart has disappeared
![ohne-start](https://user-images.githubusercontent.com/64108567/211376124-c81044d6-bda7-434b-875b-ceee6f558805.jpg)
![mit-start](https://user-images.githubusercontent.com/64108567/211376169-805ad287-cd99-4e2f-b167-f74580162186.jpg)
In the old version the autostart is included see pictures

**Comment by amiantos** [comment]
> When updating to 1,1,2 due login to autostart has disappeared
> ![ohne-start](https://user-images.githubusercontent.com/64108567/211376124-c81044d6-bda7-434b-875b-ceee6f558805.jpg)
> ![mit-start](https://user-images.githubusercontent.com/64108567/211376169-805ad287-cd99-4e2f-b167-f74580162186.jpg)
> In the old version the autostart is included see pictures

Yeah that's a known issue denoted in the changelog for this version. The package I was using, LaunchAtLogin, no longer supports macOS 10.12, so I had to drop it. Adding PiBar manually is probably a better idea in the long term for people, but if enough people complain I can look into getting it back in.

**Comment by MC-1984** [comment]
Please add the autostart option back - it is much more convenient!

**Comment by Uwedus** [comment]
Added it to Autostart
![anmelde](https://user-images.githubusercontent.com/64108567/211627206-72437c9a-6e87-47f5-97fc-32f99a24ec93.jpg)

**Comment by amiantos** [comment]
Okay I created a new issue for this other topic: https://github.com/amiantos/pibar/issues/51
