### ISSUE TITLE
Seit einigen Tagen keine Funktion mehr!!

### ISSUE THREAD

**Issue by martinkuck** [amiantos/pibar#47]
Seit einigen Tagen keine Funktion mehr, (Test Connection = Success) Trotzden Offline.

**Comment by MC-1984** [comment]
This is a duplicate of #46

**Comment by amiantos** [comment]
Hi all, I'll get to this today, thanks! Sorry for the delay.

**Comment by amiantos** [comment]
Dupe of https://github.com/amiantos/pibar/issues/46

I'll get a release in that issue for testing today.
