### ISSUE TITLE
Admin Console on ports != 80

### ISSUE THREAD

**Issue by marjue12255** [amiantos/pibar#53]
Hello

It seems that the port is not honored in the menu-entry "Admin Console". My PiHole is working on port 81, and it's configured with this port in PiBar. But the browser window what is opened when using the "Admin Console" entry is without this port.

Greetings
Marcus

**Comment by amiantos** [comment]
Curious. When saving a Pi-hole, it should be saving the raw string from the panel: https://github.com/amiantos/pibar/blob/9d2805e3929769af9e86d22dc5e70fa3caed2a28/PiBar/Views/Preferences/PiholeSettingsViewController.swift#L59

Makes me wonder if there could be something to do with when the URL is opened that is resetting the port number... https://github.com/amiantos/pibar/blob/9d2805e3929769af9e86d22dc5e70fa3caed2a28/PiBar/Views/Main%20Menu/MainMenuController.swift#L172

Anyway just thinking out loud after doing a light poke around the code in GitHub...

**Comment by marjue12255** [comment]
Hello

Sorry I was blind. I have only looked into the preferences main window. There I saw port 81. But the port hast to bo configured separately for the GUI and for the API.

Greetings
Marcus

**Comment by amiantos** [comment]
Ah, okay, no problem. Cheers!
