### ISSUE TITLE
False positive: "Partially offline" 

### ISSUE THREAD

**Issue by Coder84619** [amiantos/pibar#7]
I have two Pi-Holes on my network, and configured two in PiBar. However, the status is "Partially offline" and it lists THREE PiHoles (the two I added, plus pi-hole.local). I don't see anywhere in the GUI where I can remove "pi-hole.local".

**Comment by amiantos** [comment]
Can you send a screenshot of the Preferences screen? That's very weird. Any pi-holes that show up in the main interface should appear in the preferences so you can remove them.

If you want to go nuclear, close PiBar and open up terminal and type in `defaults delete net.amiantos.PiBar` and that'll wipe out your configuration so you can start fresh.

**Comment by Coder84619** [comment]
![PiBar-1](https://user-images.githubusercontent.com/30213019/82692774-265b8600-9c15-11ea-8a31-82d38630d901.jpg)
![piBar-2](https://user-images.githubusercontent.com/30213019/82692810-38d5bf80-9c15-11ea-93b3-3f37a0b62615.jpg)

**Comment by amiantos** [comment]
That is extremely weird. It's still there when you close PiBar and open it back up?

I'd recommend trying the terminal trick to wipe out your config and start over. If it happens again, something very strange is afoot, I'll have to go through my code to see if there is any way that could be happening.

**Comment by Coder84619** [comment]
If I quit PiBar and open it back up the mysterious third pihole entry is now gone, and all seems to be well.

**Comment by amiantos** [comment]
Well thank goodness. I'll keep this issue open though in case other people run into it, and I'll do a code audit to see if I can determine why that was happening. Thanks for letting me know about it!

**Comment by feisar-uk** [comment]
I ran into exactly the same issue. After adding my one and only Pi-Hole at address `pi.hole`, it also listed `pi-hole.local` and had 'Partially Offline' in the menubar. Quitting the app and restarted resolved it.

**Comment by sergekh42** [comment]
I had the same issue, only appeared on the first execution of the app like the others reported.
<img width="409" alt="Screen Shot 2020-05-22 at 11 59 56 AM" src="https://user-images.githubusercontent.com/9219376/82701093-552d2880-9c24-11ea-973e-8070cb6af44b.png">
<img width="937" alt="Screen Shot 2020-05-22 at 12 00 19 PM" src="https://user-images.githubusercontent.com/9219376/82701099-58c0af80-9c24-11ea-90b1-d37f0ac4fea2.png">

**Comment by roland-d** [comment]
Great work and just here to say I saw the same happen for me.

**Comment by ThomasBormans** [comment]
The exact same thing happened to me too.

**Comment by xoniq** [comment]
Got the same, when I changed the existing pi-hole.local, I had to quit and start, now its fine.

**Comment by marciopSilva** [comment]
Same here.

**Comment by bondskin** [comment]
> I have two Pi-Holes on my network, and configured two in PiBar. However, the status is "Partially offline" and it lists THREE PiHoles (the two I added, plus pi-hole.local). I don't see anywhere in the GUI where I can remove "pi-hole.local".

I had this as well, once I restarted the App, the initial/default entry disappeared

**Comment by amiantos** [comment]
A fix for this (hopefully) is now in beta: https://www.reddit.com/r/PiBar/comments/grnapv/pibar_for_macos_v11_beta/

**Comment by sergekh42** [comment]
Tested it for you, the bug has been fixed.

Deleted pibar
Deleting pibar settings - defaults delete net.amiantos.PiBar
Launched version 1.1, No extra pihole listed on first launch.

**Comment by nzkller** [comment]
Hello,

Yes the Version 1.1 fixed the issue.

I bought the application on the App Store to support, my question is went do you plan to push the new version to it? I know it's in testing phase still.

Thank you in advance and best regards,

CD

**Comment by amiantos** [comment]
@nzkller Yes, I am hoping to get 1.1 out to the App Store today, it seems like I fixed all the issues in it I was seeing in the beta.

**Comment by nzkller** [comment]
> @nzkller Yes, I am hoping to get 1.1 out to the App Store today, it seems like I fixed all the issues in it I was seeing in the beta.

Perfect!! No hurries just wanted to know!

Great job BTW I love the new version and it satisfies my control freakiness.
