### ISSUE TITLE
Menu item to open Pi-Hole Web Admin in browser

### ISSUE THREAD

**Issue by feisar-uk** [amiantos/pibar#8]
It'd be nice to have a menu item that opens the Pi-Hole web admin/dashboard in the default browser (same as https://github.com/dotWee/macOS-PiholeShortcuts does).

**Comment by amiantos** [comment]
Good idea! I actually meant to add that in (I had it in a version of the app that didn't support multiple pi-holes) but it slipped my mind before release. I'll get that in v1.1.

**Comment by Coder84619** [comment]
Ya great idea, and could it auto-login to the admin interface?

**Comment by amiantos** [comment]
I can look into that. I am not sure how to admin interface handles authentication.

**What do people most use the Pi-hole admin interface for?**

If there's a clear set of tasks that people do regularly, I could also build that functionality into PiBar.

**Comment by natelandau** [comment]
extra points if we can specify a separate url to use here.  I have a reverse proxy in front of my network which uses a different domain than I use to access the Pihole API.  

Awesome little app, btw.

**Comment by amiantos** [comment]
This feature is now in beta, complete with @natelandau's request to be able to customize the admin url per pi-hole. https://www.reddit.com/r/PiBar/comments/grnapv/pibar_for_macos_v11_beta/
